### ISSUE TITLE
Collaboration for add OCR and deck builder.

### ISSUE THREAD

**Issue by solvingproblemswithtechnology** [chinhodado/ygodb#3]
Hi,

I would like an app where I can build my decks and use ocr on card number to load it faster to the app. I would be glad to help you in this task. Are you interested?

Also, I can build a desktop app which can be connected when in the same wifi to download those decks and export them to excel, etc... But I don't find this as useful as the first part.

I hope you like the idea. Don't date in contact me for this.
Óscar.

**Comment by chinhodado** [comment]
Sorry, I am not interested.
