### ISSUE TITLE
Booster Pack cannot retrieve images

### ISSUE THREAD

**Issue by Vorpalblada** [chinhodado/ygodb#5]
Yugioh wiki is using {{Set list}} instead of using wikiatable

**Comment by Vorpalblada** [comment]
http://i.imgur.com/TZViC3b.jpg
Here's a screenshot from my device (Android 5.1)

**Comment by chinhodado** [comment]
Thanks for reporting, it's fixed now.

**Comment by Vorpalblada** [comment]
Thanks for the quick response
